version: '3.6'
services:
  wallet:
    container_name: 'wallet'
    build: ./wallet
    ports:
      - '8888:8888'
    volumes:
      - ./tmp/wallet/:/opt/application/data/
  postgres:
    container_name: 'postgres'
    image: postgres:13.3-alpine
    ports:
      - '5432:5432'
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
  hapi:
    container_name: 'hapi'
    image: node:14.2.0
    ports:
      - '9090:9090'
    volumes:
      - ./tmp/hapi/node_modules/:/app/node_modules/
      - type: bind
        source: ./hapi
        target: /app
    working_dir: /app
    command: bash -c "yarn && yarn watch"
    environment:
      HAPI_SERVER_PORT: '${HAPI_SERVER_PORT}'
      HAPI_SERVER_ADDRESS: '${HAPI_SERVER_ADDRESS}'
      HAPI_NETWORK_API: '${HAPI_NETWORK_API}'
      HAPI_NETWORK_CHAIN_ID: '${HAPI_NETWORK_CHAIN_ID}'
      HAPI_NETWORK_BASE_ACCOUNT: '${HAPI_NETWORK_BASE_ACCOUNT}'
      HAPI_NETWORK_BASE_PASSWORD: '${HAPI_NETWORK_BASE_PASSWORD}'
      HAPI_NETWORK_WALLET_URL: '${HAPI_NETWORK_WALLET_URL}'
      HAPI_HASURA_URL: '${HAPI_HASURA_URL}'
      HAPI_HASURA_ADMIN_SECRET: '${HAPI_HASURA_ADMIN_SECRET}'
  hasura:
    container_name: 'hasura'
    image: hasura/graphql-engine:v2.0.6.cli-migrations-v3
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    volumes:
      - ./hasura/migrations:/migrations
      - ./hasura/metadata:/metadata
      - ./hasura/seeds:/seeds
    environment:
      HASURA_GRAPHQL_DATABASE_URL: '${HASURA_GRAPHQL_DATABASE_URL}'
      HASURA_GRAPHQL_MIGRATIONS_DIR: /migrations
      HASURA_GRAPHQL_METADATA_DIR: /metadata
      HASURA_GRAPHQL_SEEDS_DIR: /seeds
      HASURA_GRAPHQL_ACTION_BASE_URL: '${HASURA_GRAPHQL_ACTION_BASE_URL}'
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      HASURA_GRAPHQL_ADMIN_SECRET: '${HASURA_GRAPHQL_ADMIN_SECRET}'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: '${HASURA_GRAPHQL_UNAUTHORIZED_ROLE}'
      # Local Development Configurations It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ENABLE_LOGGING: 'true'
  testnet:
    container_name: 'testnet'
    image: eoscostarica506/proton-local
    ports:
      - '8888:8888'
